config/routes.rb
Rails.application.routes.draw do
  resources :queries
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Query was successfully created.' }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_params
      params.require(:query).permit(:name, :email, :phone, :place, :ask)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/home/index.html.erb
<br>
<div class="text-center shadow-lg p-3 mb-5 rounded container" role="alert">
  <h4><strong>Test Your Aim and Boost Up!- 
  <span>
 
  <a href="https://github.com/ashutoshpith" class= "badge badge-outline-primary">ashutoshpith</a>
  </span>
  <%= link_to  "Ask Query", new_query_path, class: "btn btn-outline-info" %>

  </strong></h4>
</div>
<div>
</div>
<div id="quick" class="text-center container bg-warning" role="alert">
  <p>Click on the points as quickly as you can !</p>

</div>
<br>
<div id="time" class="container" role="alert">
  <p class="bold">Your time : <span id="timeTaken"></span></p>
  <div class="container" id="shape" onmousedown="bleep.play()"></div>
</div>

   <script type="text/javascript">
            var start = new Date().getTime();
            function makeShapeAppear() {
                var top = Math.random() * 400;
                var left = Math.random() * 400;
                var width = (Math.random() * 200) + 100;
                document.getElementById("shape").style.backgroundColor = "black";
                document.getElementById("shape").style.top = top + "px";
                document.getElementById("shape").style.left = left + "px";
                document.getElementById("shape").style.display = "block";
                start = new Date().getTime();
            }
            function appearAfterDelay() {
                setTimeout(makeShapeAppear,200);
            }
            appearAfterDelay();
            document.getElementById("shape").onclick = function() {
                document.getElementById("shape").style.display = "none";
                var end = new Date().getTime();
                var timeTaken = (end - start) / 1000;
                document.getElementById("timeTaken").innerHTML = timeTaken + "s";
                appearAfterDelay();
            }
          var bleep=new Audio();
          bleep.src="gun.wav";
          
        </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aim Booster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/queries/_form.html.erb
<div class="container">
<%= form_with(model: query, local: true) do |form| %>
  <% if query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
      <% query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :ask %>
    <%= form.text_field :ask %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/queries/edit.html.erb
<h1>Editing Query</h1>

<%= render 'form', query: @query %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Ask</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Place</th>
      <th>Ask</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.name %></td>
        <td><%= query.email %></td>
        <td><%= query.phone %></td>
        <td><%= query.place %></td>
        <td><%= query.ask %></td>
       
        <td><%= link_to 'Edit', edit_query_path(query) %></td>
        <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>
</div>

app/views/queries/new.html.erb
<div class="container">

<h1>Ask</h1>

<%= render 'form', query: @query %>

<%= link_to 'Back', queries_path %>
</div>

app/views/queries/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @query.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @query.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @query.phone %>
</p>

<p>
  <strong>Place:</strong>
  <%= @query.place %>
</p>

<p>
  <strong>Ask:</strong>
  <%= @query.ask %>
</p>

<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>
</div>